# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/OneDrive/LWX/Project/MCS51/vivado/pro_five/pro_five.srcs/sources_1/ip/rom_16kx8/rom_16kx8.xci
# IP: The module: 'rom_16kx8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/OneDrive/LWX/Project/MCS51/vivado/pro_five/pro_five.gen/sources_1/ip/rom_16kx8/rom_16kx8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_16kx8'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/OneDrive/LWX/Project/MCS51/vivado/pro_five/pro_five.srcs/sources_1/ip/rom_16kx8/rom_16kx8.xci
# IP: The module: 'rom_16kx8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/OneDrive/LWX/Project/MCS51/vivado/pro_five/pro_five.gen/sources_1/ip/rom_16kx8/rom_16kx8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_16kx8'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
